### ISSUE TITLE
Angular 8 build error

### ISSUE THREAD

**Issue by avmaisak** [codaline-io/angular-stl-model-viewer#303]
`
node_modules/three/src/core/BufferAttribute.d.ts:21:6 - error TS1086: An accessor cannot be declared in an ambient context.

21  set needsUpdate( value: boolean );

node_modules/three/src/core/InterleavedBufferAttribute.d.ts:19:6 - error TS1086: An accessor cannot be declared in an ambient context.

19  get count(): number;

node_modules/three/src/core/InterleavedBufferAttribute.d.ts:20:6 - error TS1086: An accessor cannot be declared in an ambient context.

20  get array(): ArrayLike<number>;

node_modules/three/src/renderers/webgl/WebGLAttributes.d.ts:6:43 - error TS2304: Cannot find name 'WebGL2RenderingContext'.

6  constructor( gl: WebGLRenderingContext | WebGL2RenderingContext );

node_modules/three/src/renderers/webgl/WebGLUtils.d.ts:3:43 - error TS2304: Cannot find name 'WebGL2RenderingContext'.

3  constructor( gl: WebGLRenderingContext | WebGL2RenderingContext, extensions: any, capabilities: any );

`

**three package - 0.111.0**

**Comment by avmaisak** [comment]
ping

**Comment by Liotarne** [comment]
up

**Comment by KillerCodeMonkey** [comment]
refactored the project to work with angular 9 and latest threejs. 

The input props changed --> see releases section.

no errors in production build and the example.

Please try it out
