### ISSUE TITLE
Stl file doesn't show correctly

### ISSUE THREAD

**Issue by lhf552004** [codaline-io/angular-stl-model-viewer#320]
**Describe the bug**
Hi, thanks for your library, but there is something wrong when showing my stl file. The pictures looks differently.
Here is my stl file:
[tubing_asm.zip](https://github.com/tevim/angular-stl-model-viewer/files/4014802/tubing_asm.zip)
Could you kindly have a look?  I appreicate that.

**Screenshots**
![image](https://user-images.githubusercontent.com/10030850/71650033-60071f80-2d4e-11ea-885b-8394006b2dc1.png)

**Original View**
![image](https://user-images.githubusercontent.com/10030850/71650117-eb80b080-2d4e-11ea-89a2-7cf85599a09a.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version :
    "angular-stl-model-viewer": "^0.6.0",
    "three": "^0.106.2",

**Comment by KillerCodeMonkey** [comment]
just change meshoptions (scaling and position)
