### ISSUE TITLE
How to force rerender of model when stlModel changes ?

### ISSUE THREAD

**Issue by charkops** [codaline-io/angular-stl-model-viewer#389]
**Describe the bug**
Hello, i am building a small app where the main feature is to display .stl Models uploaded by the user. I can successfully display a single uploaded model, but when the stlModel property value changes (it is binded to a string which represent a served file from a server) the viewer doesn't change the displayed object). Is there a way to force - render on the viewer in order to display the latest uploaded model ?

**To Reproduce**
1) Create a small app with a stl viewer, in which the [stlModel] property is binded to an input.
2) Change input to a valid stlModel
3) stl Viewer does not render the correct Model, continues to display the first binded model

**Expected behavior**
Viewer should render a new model everytime the input (stlModel property) changes 

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - Firefox & Chrome (latest)

**Comment by untmdme** [comment]
I'm looking for the exact same thing. :(

**Comment by charkops** [comment]
> I have found a workaround to this by using arrays.
> 
> the template looks like this
> 
> ```
>  <stl-model-viewer *ngFor="let stl of STLs"  [stlModel]=stl.file [material]=material></stl-model-viewer>
> ```
> 
> And in the ts I have an array of objects.
> 
> ```ts
> STLs = [{file : this.selectedFile, update: 0}] 
> ```
> 
> where I update the STL path itself. The update key is being used to force updates when the filepath stays the same but I need to update the material.

Thank you for the comment, i will try your method and see if it suits my needs.

Just to inform other users in the future:

For reasons i cannot comprehend, if i use a *ngIf directive on the stl-viewer with binded model property, the first time it "shows" it can successfully render the selected stlModel. So, for now, the "workaround" is simply to set the variable controlling *ngIf to false and after a small amount of time to re-set it to true (using a setTimeout(..., 10ms) or something), thus triggering a rerender. 

Disgusting code, but it works :)
