### ISSUE TITLE
Multiple Components (different file paths)

### ISSUE THREAD

**Issue by christiandrotor** [codaline-io/angular-stl-model-viewer#395]
**Describe the bug**
The bug appears if the component is called at least twice with different files

**To Reproduce**
Below is a div with two seperate
```
 <div class="row">
    <stl-model-viewer [stlModel]="models.get(stlModelNames[0]).stlModelPath"
                      [camera]="models.get(stlModelNames[0]).camera"
                      [light]="models.get(stlModelNames[0]).light"
                      [material]="models.get(stlModelNames[0]).material"
                      [meshOptions]="models.get(stlModelNames[0]).meshOptions"
                      [scene]="models.get(stlModelNames[0]).scene"
                      id="teapot"
                      class="col-5"></stl-model-viewer>
    <span class="col-2"></span>
    <stl-model-viewer [stlModel]="models.get(stlModelNames[1]).stlModelPath"
                      [camera]="models.get(stlModelNames[0]).camera"
                      [light]="models.get(stlModelNames[0]).light"
                      [material]="models.get(stlModelNames[0]).material"
                      [meshOptions]="models.get(stlModelNames[0]).meshOptions"
                      [scene]="models.get(stlModelNames[0]).scene"
                      id="other"
                      class="col-5"></stl-model-viewer>
  </div>
```
**Expected behavior**
2 separate components that display one single model that was assigned to the component

**Screenshots**
![image](https://user-images.githubusercontent.com/32677219/82316856-6a435680-999b-11ea-943e-314e033b1654.png)
![image](https://user-images.githubusercontent.com/32677219/82317335-12f1b600-999c-11ea-853b-6e58a4220fab.png)

(Should be just a teapot and other part but the other part is in the teapot and after moving the other part the teapot is in the other part)

Thanks for your hard work in this library. It's a lot of fun!

**Comment by KillerCodeMonkey** [comment]
if you pass the same scene, everything is added to that one scene ;-)
