### ISSUE TITLE
OnChanges method

### ISSUE THREAD

**Issue by jmaster03** [codaline-io/angular-stl-model-viewer#441]
Hi, I'm building a simple .stl uploader app. I've no errors with this module but when a change the file the viewer doesn't change. Is there an OnChange method example for this component?

**Comment by KillerCodeMonkey** [comment]
currently not. but feel free to create a pr :)
  
​

**Comment by KillerCodeMonkey** [comment]
As a workaround just hide and reinit the component.

**Comment by jmaster03** [comment]
Thank you UwU
