### ISSUE TITLE
 The target entry-point "angular-stl-model-viewer" has missing dependencies

### ISSUE THREAD

**Issue by tekilla667** [codaline-io/angular-stl-model-viewer#447]
So I had the stl-model-viewer run all good, the 3d model was being displayed properly and angular was running with no errors.
However I installed angular cdk with
`ng add @angular/cdk`
After that I wanted to build my project with ng build and got the error

```
ERROR in The target entry-point "angular-stl-model-viewer" has missing dependencies:
 - three
 - three/examples/jsm/loaders/STLLoader
 - three/examples/jsm/controls/OrbitControls
```
I tried reinstalling the stl viewer with 
```
yarn add angular-stl-model-viewer
npm install angular-stl-model-viewer
```
but it didn't help

My package.json does contain three declaration:
```

{
  "name": "client",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.2.4",
    "@angular/cdk": "^10.2.7",
    "@angular/common": "~10.2.4",
    "@angular/compiler": "~10.2.4",
    "@angular/core": "~10.2.4",
    "@angular/forms": "~10.2.4",
    "@angular/platform-browser": "~10.2.4",
    "@angular/platform-browser-dynamic": "~10.2.4",
    "@angular/router": "~10.2.4",
    "angular-stl-model-viewer": "^3.2.0",
    "angular-toastr": "^2.1.1",
    "bootstrap": "4.1.1",
    "font-awesome": "^4.7.0",
    "ngx-bootstrap": "^6.2.0",
    "ngx-toastr": "^13.2.0",
    "rxjs": "~6.5.4",
    "three": "^0.125.2",
    "tslib": "^2.0.0",
    "uuid": "^8.3.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1002.2",
    "@angular/cli": "~10.2.2",
    "@angular/compiler-cli": "~10.2.4",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.7"
  }
}

```

Any ideas how can I make it work back again?

**Comment by tekilla667** [comment]
Also: when I browse my node_modules folder I can't find any folder inside that contains "three" in its name

**Comment by KillerCodeMonkey** [comment]
Then try to remove The node_modules folder an Reinstall your deps


Am 26.02.2021 in 14:48, tekilla667 <notifications@github.com> schrieb:

Also: when I browse my node_modules folder I can't find any folder inside
that contains "three" in its name

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/codaline-io/angular-stl-model-viewer/issues/447#issuecomment-786657830>,
or unsubscribe

**Comment by tekilla667** [comment]
I ran the` npm install angular-stl-model-viewer first` and then `yarn add angular-stl-model-viewer`. It did the trick, now I have the three folder in node modules and everything runs smoothly again. Thanks anyway bro!
