### ISSUE TITLE
NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

### ISSUE THREAD

**Issue by 503Dev** [codaline-io/angular-stl-model-viewer#470]
**Describe the bug**
Using Angular 11.x on a working project I was able to use npm to install angular-stl-model-viewer.  Once done, I imported it as I would normally:

import { StlModelViewerModule } from "../../node_modules/angular-stl-model-viewer/angular-stl-model-viewer";

and then added this to imports: StlModelViewerModule,

When I run ng serve I get this error:
```
Error: node_modules/angular-stl-model-viewer/lib/angular-stl-model-viewer.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library which declares StlModelViewerModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

```

**Desktop (please complete the following information):**
 - OS: Win 10
 - Angular: 11.x

**Additional context**
I attempted to reinstall via both npm and yarn in case I had an install issue.  I also tried importing the Module public-api instead as I saw in the example, same exact error.

**Comment by KillerCodeMonkey** [comment]
which version of angular-stl-model-viewer do you use?

try v3.2.0 for angular 11 instead v4.

**Comment by 503Dev** [comment]
@KillerCodeMonkey  - Thanks for the fast response.  I tried removing node_modules, forcing 3.2.0 and npm install.  Looks to have downloaded 3.2.0 however I still get the same error when I do ng serve my project.  This error:

```
Error: node_modules/angular-stl-model-viewer/lib/angular-stl-model-viewer.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of TablesModule, but could not be resolved to an NgModule class.

This likely means that the library which declares StlModelViewerModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class StlModelViewerModule {
```

It's Angular 11.0.2 and I am sure I am doing something wrong but I can't figure out what...

**Comment by KillerCodeMonkey** [comment]
so i just created an empty project + angular 11 and v3.2.0 and v4 is working as expected

**Comment by 503Dev** [comment]
Thanks.  I also did the same and had no problems.  Your code is just great something is weird in my project which I can't figure out but I just started a new project and built around your plugin, thank you for everything.
