### ISSUE TITLE
On zoom stl file it shows incorrectly burst

### ISSUE THREAD

**Issue by acharyaks90** [codaline-io/angular-stl-model-viewer#601]
**Describe the bug**
On zoom at certain point of time file become burst 

**To Reproduce**

1 Zoom it till the time it burst
<img width="1168" alt="image" src="https://github.com/user-attachments/assets/f75315e2-c05a-4a2b-91e7-b34cc17b9245">
2. Post zoom -
3. 
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/6e12812a-af05-4afc-a644-7d193a5dbaca">

**Expected behavior**

**Screenshots**
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/94b54678-b0cc-410f-962f-d152c8ceef10">

Link for stackblitz
https://stackblitz.com/~/github.com/acharyaks90/stl_viewer

**Comment by KillerCodeMonkey** [comment]
i guess this is the ordinary behavior when you zoom "into" the model. so your camera dives into your model?

We are just adding all the default stuff threejs offers to the scene, basic controls (object controls), a default camera and so on.

Those defaults are not fitting everybody's needs, so feel free to set your own controls/camera.
